---
- name: Converge
  hosts: all
  vars:
   cron_admin: root@localhost
  tasks:
    - name: install crontab
      dnf:
        name:
          - cronie
          - php
    - name: create apache user
      user:
        name: apache
        state: present
    - name: "Include config-lims-us3-user"
      include_role:
        name: "config-lims-us3-user"
