---
us3_db_host: "localhost"
us3_db_name: "newus3"
us3_db_user: "new_us3user"

gbl_db_host: "localhost"
gbl_db_name: "gfac"
gbl_db_user: "gfac"

lims3_db_user: "lims3_admin"

server_name: "{{ hostname }}"

sql_ssl_ca: "/etc/my.cnf.d/ssl/ca-cert.pem"
sql_ssl_cert: "/etc/my.cnf.d/ssl/server-cert.pem"
sql_ssl_key: "/etc/my.cnf.d/ssl/server-key.pem"

# admin users
admin_users:
  - user: "us3demeler"
    fname: "Borries"
    lname: "Demeler"
    address: "32 Campus Drive"
    city: "Missoula"
    state: "MT"
    zip: "59812"
    country: "US"
    phone: "406-285-1935"
    password: "{{ admins_db_pass }}"
    organization: "University of Montana"
    activated: "1"
    userlevel: "4"
    email: "demeler@gmail.com"

  - user: "us3savelyev"
    fname: "Alexey"
    lname: "Savelyev"
    address: "32 Campus Drive"
    city: "Missoula"
    state: "MT"
    zip: "59812"
    country: "US"
    password: "{{ admins_db_pass }}"
    phone: "555-555-5555"
    organization: "Unversity of Montana"
    activated: "1"
    userlevel: "4"
    email: "alexsav.science@gmail.com"

  - user: "us3gorbet"
    fname: "Gary"
    lname: "Gorbet"
    address: "32 Campus Drive"
    city: "Missoula"
    state: "MT"
    password: "{{ admins_db_pass }}"
    zip: "59812"
    country: "US"
    phone: "832-466-9211"
    organization: "University of Montana"
    activated: "1"
    userlevel: "4"
    email: "gegorbet@gmail.com"

  - user: "us3brookes"
    fname: "Emre"
    lname: "Brookes"
    address: "32 Campus Drive"
    city: "Missoula"
    state: "MT"
    password: "{{ admins_db_pass }}"
    zip: "59812"
    country: "US"
    phone: "406-203-0055"
    organization: "University of Montana"
    activated: "1"
    userlevel: "4"
    email: "emre.brookes@umontana.edu"
