---
- name: Get rpm package facts
  package_facts:
    manager: auto

- name: install slurm dependencies
  dnf:
        enablerepo: powertools
        name:
                - globus-gram-job-manager-slurm
                - munge-devel
                - munge
                - lua-devel
                - readline-devel
                - pam-devel
                - perl-ExtUtils-MakeMaker
                - perl-Switch
                - rpm-build
                - make
                - gcc
                - mariadb-devel
                - python3
        state: present
        update_cache: yes

- name: check if munge key already exists
  stat:
    path: /etc/munge/munge.key
  register: munge_key

- name: create munge key
  shell: "/usr/sbin/create-munge-key"
  when: munge_key.stat.exists == false
  notify:
    - restart munge

- name: get slurm source
  get_url:
        url: "https://download.schedmd.com/slurm/slurm-{{ slurm_ver }}.tar.bz2"
        dest: /tmp


- name: Get slurm package checksum
  stat:
    path: "/tmp/slurm-{{ slurm_ver }}.tar.bz2"
    checksum_algorithm: "{% if slurm_md5 != 'none' %}md5{% else %}sha1{% endif %}"
    get_checksum: yes
  register: slurm_integrity
  when: slurm_md5 != 'none' or slurm_sha1 != 'none'

- name: Checksum error
  debug:
    msg:
      - "Hash not the same"
      - "{{ slurm_integrity.stat.checksum }}"
      - "{{ slurm_hash }}"
  when: "(slurm_md5 != 'none' or slurm_sha1 != 'none') and slurm_integrity.stat.checksum != slurm_hash"

- name: remove old slurm packages
  shell:
    cmd: "rm -fr /root/rpmbuild/RPMS/x86_64/slurm*"
    warn: false
  ignore_errors: yes
  when: "('slurm' not in ansible_facts.packages and slurm_hash == 'none' )  or ('slurm' not in ansible_facts.packages and slurm_integrity.stat.checksum == slurm_hash)"

- name: build slurm packages
  shell: "rpmbuild -ta /tmp/slurm-{{ slurm_ver }}.tar.bz2"
  when: "('slurm' not in ansible_facts.packages and slurm_hash == 'none' )  or ('slurm' not in ansible_facts.packages and slurm_integrity.stat.checksum == slurm_hash)"

- name: install built packages
  shell:
    chdir: /root/rpmbuild/RPMS/x86_64
    cmd: "yum install --allowerasing ./slurm*  -y"
    warn: false
     

  when: "'slurm' not in ansible_facts.packages"


- name: Create slurm user
  user:
        name: slurm
        state: present
        system: yes

- name: create slurm log dir
  file:
        path: /var/log/slurm/
        owner: slurm
        group: slurm
        state: directory

- name: create slurm spool dir
  file:
        path: /var/spool/slurm
        owner: slurm
        group: slurm
        state: directory

- name: config slurm.conf
  template:
        src: slurm.conf.j2
        dest: /etc/slurm/slurm.conf
        backup: yes
  notify:
        - restart slurmd
        - restart slurmctld

- name: Enable slurm
  service:
    name : '{{ item }}'
    enabled: yes
    state: started
  with_items:
    - slurmd
    - slurmctld
    - munge
    
    
     