---
- name: Converge
  hosts: all
  vars:
    - slurm_ver: 20.02.2
    - slurm_md5: c57b67b252ec6b64509fafe6453bf716
  tasks:
    - name: "install mariadb"
      dnf:
        name:
          - mariadb-devel
    - name: "Get epel"
      include_role:
        name: "geerlingguy.repo-epel"
    - name: "Include config-lims-slurm"
      include_role:
        name: "config-lims-slurm"
